spring:
  datasource:
    url: jdbc:mariadb:pillsolution.cvjiwbuuly4r.ap-northeast-2.rds.amazonaws.com #jdbc:h2:tcp://localhost/~/pillSolution
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver #org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket: pill-solution-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
