spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pillSolution
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: AKIA36W7FXMSJPPJ4FW3
      secret-key: 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
    s3:
      bucket: pill-solution-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false